
marsupilami:
    resource: "@MarsupilamiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

places:
    type:     rest
    resource: MarsupilamiBundle\Controller\ApiController
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

