<?php

namespace MarsupilamiBundle\Repository;

/**
 * MarsupilamiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarsupilamiRepository extends \Doctrine\ORM\EntityRepository
{
/*
    function catVDQL()
    {
        $query=$this->getEntityManager()->createQuery("select a from EshopUserBundle:Produit a where a.idCategorie=4");


        return $query->getResult();
    }
*/
}
